# Generated by Django 5.0.6 on 2024-07-06 18:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitarInv', models.BooleanField(default=True, verbose_name='Habilitar Formulario')),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitada', models.BooleanField(default=False)),
                ('titulo', models.CharField(max_length=100)),
                ('resumen', models.TextField(max_length=500)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('guia_externo', models.CharField(max_length=250)),
                ('documentacion', models.FileField(blank=True, null=True, upload_to='documento/proyecto', verbose_name='Agregar Documentacion')),
                ('estado', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=10)),
                ('jurado_1_aprobado', models.BooleanField(default=False)),
                ('jurado_2_aprobado', models.BooleanField(default=False)),
                ('jurado_3_aprobado', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_estudiante', to=settings.AUTH_USER_MODEL)),
                ('jurado_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_jurado_1', to=settings.AUTH_USER_MODEL)),
                ('jurado_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_jurado_2', to=settings.AUTH_USER_MODEL)),
                ('jurado_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_jurado_3', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_tutor', to=settings.AUTH_USER_MODEL)),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg_mod_graduacion.modalidad', verbose_name='Seleccione Una Modalidad')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_estudiante', to=settings.AUTH_USER_MODEL)),
                ('jurado_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_jurado_1', to=settings.AUTH_USER_MODEL)),
                ('jurado_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_jurado_2', to=settings.AUTH_USER_MODEL)),
                ('jurado_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_jurado_3', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_tutor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentarioactividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actcomentario', models.TextField(max_length=1000, verbose_name='Ingrese Comentario Retroalimentativo')),
                ('actfecha_post', models.DateTimeField(auto_now_add=True)),
                ('actproyecto_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='seg_mod_graduacion.actividad')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-actfecha_post'],
            },
        ),
        migrations.CreateModel(
            name='InvCientifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invtitulo', models.CharField(max_length=150, verbose_name='Agregar Titulo')),
                ('slug', models.SlugField(unique=True)),
                ('invfecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('invdescripcion', models.TextField(blank=True, verbose_name='Agregar una Descripcion')),
                ('invdocumentacion', models.FileField(blank=True, null=True, upload_to='documento/proyecto', verbose_name='Agregar Documentacion')),
                ('invdestacado', models.BooleanField(default=True, verbose_name='Destacar Formulario')),
                ('investado', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario relacionado')),
                ('invmodalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg_mod_graduacion.modalidad', verbose_name='Seleccione Una Modalidad')),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioInvCientifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invcomentario', models.TextField(max_length=1000, verbose_name='Ingrese Comentario Retroalimentativo')),
                ('invfecha_post', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invproyecto_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg_mod_graduacion.invcientifica')),
            ],
            options={
                'ordering': ['-invfecha_post'],
            },
        ),
        migrations.CreateModel(
            name='PerfilProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertitulo', models.CharField(max_length=150, verbose_name='Agregar Titulo Perfil')),
                ('slug', models.SlugField(unique=True)),
                ('perfecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('perdescripcion', models.TextField(blank=True, verbose_name='Agregar una Descripcion')),
                ('perdocumentacion', models.FileField(blank=True, null=True, upload_to='documento/proyecto', verbose_name='Agregar Documentacion')),
                ('perestado', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=10)),
                ('permodalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg_mod_graduacion.modalidad', verbose_name='Seleccione Una Modalidad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario relacionado')),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percomentario', models.TextField(max_length=1000, verbose_name='Ingrese Comentario Retroalimentativo')),
                ('perfecha_post', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('perproyecto_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='seg_mod_graduacion.perfilproyecto')),
            ],
            options={
                'ordering': ['-perfecha_post'],
            },
        ),
    ]
