# Generated by Django 5.0.6 on 2024-07-06 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='guia_externo',
            field=models.CharField(default='-----------', max_length=250),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='modalidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seg_mod_graduacion.modalidad', verbose_name='Seleccione Una Modalidad'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='resumen',
            field=models.TextField(default='Describa el Proyecto...', max_length=500),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='titulo',
            field=models.CharField(default='------', max_length=100),
        ),
    ]
