# Generated by Django 5.0.6 on 2024-07-09 14:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0002_alter_actividad_guia_externo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadRepositorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitada', models.BooleanField(default=False)),
                ('titulo', models.CharField(default='------', max_length=100)),
                ('resumen', models.TextField(default='Describa el Proyecto...', max_length=500)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('guia_externo', models.CharField(default='-----------', max_length=250)),
                ('documentacion', models.FileField(blank=True, null=True, upload_to='documento/proyecto', verbose_name='Agregar Documentacion')),
                ('estado', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=10)),
                ('jurado_1_aprobado', models.BooleanField(default=False)),
                ('jurado_2_aprobado', models.BooleanField(default=False)),
                ('jurado_3_aprobado', models.BooleanField(default=False)),
                ('anio_ingreso', models.IntegerField()),
                ('anio_egreso', models.IntegerField()),
                ('numero_acta', models.CharField(max_length=50)),
                ('nota_aprobacion', models.DecimalField(decimal_places=2, max_digits=4)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_estudiante', to=settings.AUTH_USER_MODEL)),
                ('jurado_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_jurado_1', to=settings.AUTH_USER_MODEL)),
                ('jurado_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_jurado_2', to=settings.AUTH_USER_MODEL)),
                ('jurado_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_jurado_3', to=settings.AUTH_USER_MODEL)),
                ('modalidad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seg_mod_graduacion.modalidad', verbose_name='Seleccione Una Modalidad')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_tutor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
