# Generated by Django 5.0.6 on 2024-07-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0003_actividadrepositorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadrepositorio',
            name='periodo',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='invcientifica',
            name='invdescripcion',
            field=models.TextField(blank=True, verbose_name='Agregar una Descripcion Breve'),
        ),
    ]
