# Generated by Django 5.0.6 on 2024-07-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0004_actividadrepositorio_periodo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invcientifica',
            name='invdestacado',
        ),
        migrations.RemoveField(
            model_name='invcientifica',
            name='invmodalidad',
        ),
    ]
