# Generated by Django 5.0.6 on 2024-07-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0005_remove_invcientifica_invdestacado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='titulo',
            field=models.CharField(default='------', max_length=450),
        ),
        migrations.AlterField(
            model_name='actividadrepositorio',
            name='titulo',
            field=models.CharField(default='------', max_length=450),
        ),
        migrations.AlterField(
            model_name='invcientifica',
            name='invtitulo',
            field=models.CharField(max_length=450, verbose_name='Agregar Titulo'),
        ),
        migrations.AlterField(
            model_name='perfilproyecto',
            name='pertitulo',
            field=models.CharField(max_length=450, verbose_name='Agregar Titulo Perfil'),
        ),
    ]
