# Generated by Django 5.0.6 on 2024-07-19 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0006_alter_actividad_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadcontrol',
            name='modalidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seg_mod_graduacion.modalidad', verbose_name='Seleccione Una Modalidad'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg_mod_graduacion.modalidad'),
        ),
    ]
