# Generated by Django 5.0.6 on 2024-07-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0007_actividadcontrol_modalidad_alter_actividad_modalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='guia_externo',
            field=models.CharField(default='Ninguno', max_length=250),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='resumen',
            field=models.TextField(default='Describa breve de su proyecto ....', max_length=500),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='titulo',
            field=models.CharField(default='Agrege el titulo de su proyecto....', max_length=450),
        ),
    ]
