# Generated by Django 5.0.6 on 2024-07-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0008_alter_actividad_guia_externo_alter_actividad_resumen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadrepositorio',
            name='documentacion',
            field=models.FileField(blank=True, null=True, upload_to='documento/repositorios', verbose_name='Agregar Documentacion'),
        ),
        migrations.AlterField(
            model_name='actividadrepositorio',
            name='nota_aprobacion',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
