# Generated by Django 5.0.6 on 2024-07-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0009_alter_actividadrepositorio_documentacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadrepositorio',
            name='periodo',
            field=models.CharField(default='Asignar', max_length=450),
        ),
    ]
