# Generated by Django 5.0.6 on 2024-07-31 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0011_alter_actividadrepositorio_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadrepositorio',
            name='periodo',
            field=models.CharField(max_length=50),
        ),
    ]
