# Generated by Django 5.0.6 on 2024-08-04 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0012_alter_actividadrepositorio_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadcontrol',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg_mod_graduacion.modalidad', verbose_name='Seleccione Una Modalidad'),
        ),
    ]
