# Generated by Django 5.0.6 on 2024-08-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0013_alter_actividadcontrol_modalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='resumen',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='titulo',
            field=models.CharField(max_length=450),
        ),
    ]
