# Generated by Django 5.0.6 on 2024-08-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0014_alter_actividad_resumen_alter_actividad_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadrepositorio',
            name='guia_externo',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='actividadrepositorio',
            name='resumen',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='actividadrepositorio',
            name='titulo',
            field=models.CharField(max_length=450),
        ),
    ]
