# Generated by Django 5.0.6 on 2024-07-22 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='anio_ingreso',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gestion_ingreso',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ru',
        ),
    ]
