# Generated by Django 5.0.6 on 2024-08-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interccion_social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_fase_proyecto',
            name='S_Fase',
            field=models.CharField(max_length=100, verbose_name='Fase o Etapa del Proyecto'),
        ),
        migrations.AlterField(
            model_name='t_gestion',
            name='S_Gestion',
            field=models.CharField(max_length=100, verbose_name='Gestion y periodo'),
        ),
        migrations.AlterField(
            model_name='t_tipo_proyecto',
            name='S_Tipo',
            field=models.CharField(max_length=100, verbose_name='Tipo de Investigación Social.'),
        ),
    ]
